/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const T__1 = IDL.Variant({
  'contact' : IDL.Null,
  'site_visit' : IDL.Null,
  'property_details' : IDL.Null,
  'general' : IDL.Null,
  'sell_property' : IDL.Null,
});
export const Time = IDL.Int;
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'leadType' : T__1,
  'name' : IDL.Text,
  'propertyId' : IDL.Opt(IDL.Nat),
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const T__2 = IDL.Variant({
  'sold' : IDL.Null,
  'available' : IDL.Null,
  'under_negotiation' : IDL.Null,
});
export const T = IDL.Variant({
  'commercial_land' : IDL.Null,
  'house' : IDL.Null,
  'residential_plot' : IDL.Null,
  'warehouse' : IDL.Null,
  'franchise_outlet' : IDL.Null,
});
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'status' : T__2,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'bedrooms' : IDL.Opt(IDL.Nat),
  'area' : IDL.Float64,
  'description' : IDL.Text,
  'areaUnit' : IDL.Text,
  'category' : T,
  'priceUnit' : IDL.Text,
  'price' : IDL.Nat,
  'location' : IDL.Text,
});
export const SellPropertyRequest = IDL.Record({
  'id' : IDL.Nat,
  'ownerName' : IDL.Text,
  'propertyType' : T,
  'area' : IDL.Float64,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'expectedPrice' : IDL.Nat,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getAllSellRequests' : IDL.Func(
      [],
      [IDL.Vec(SellPropertyRequest)],
      ['query'],
    ),
  'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getPropertiesByCategory' : IDL.Func([T], [IDL.Vec(Property)], ['query']),
  'getProperty' : IDL.Func([IDL.Nat], [Property], ['query']),
  'submitLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, T__1, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'submitSellPropertyRequest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        T,
        IDL.Text,
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const T__1 = IDL.Variant({
    'contact' : IDL.Null,
    'site_visit' : IDL.Null,
    'property_details' : IDL.Null,
    'general' : IDL.Null,
    'sell_property' : IDL.Null,
  });
  const Time = IDL.Int;
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'leadType' : T__1,
    'name' : IDL.Text,
    'propertyId' : IDL.Opt(IDL.Nat),
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const T__2 = IDL.Variant({
    'sold' : IDL.Null,
    'available' : IDL.Null,
    'under_negotiation' : IDL.Null,
  });
  const T = IDL.Variant({
    'commercial_land' : IDL.Null,
    'house' : IDL.Null,
    'residential_plot' : IDL.Null,
    'warehouse' : IDL.Null,
    'franchise_outlet' : IDL.Null,
  });
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'status' : T__2,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'bedrooms' : IDL.Opt(IDL.Nat),
    'area' : IDL.Float64,
    'description' : IDL.Text,
    'areaUnit' : IDL.Text,
    'category' : T,
    'priceUnit' : IDL.Text,
    'price' : IDL.Nat,
    'location' : IDL.Text,
  });
  const SellPropertyRequest = IDL.Record({
    'id' : IDL.Nat,
    'ownerName' : IDL.Text,
    'propertyType' : T,
    'area' : IDL.Float64,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'expectedPrice' : IDL.Nat,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getAllSellRequests' : IDL.Func(
        [],
        [IDL.Vec(SellPropertyRequest)],
        ['query'],
      ),
    'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getPropertiesByCategory' : IDL.Func([T], [IDL.Vec(Property)], ['query']),
    'getProperty' : IDL.Func([IDL.Nat], [Property], ['query']),
    'submitLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, T__1, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'submitSellPropertyRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          T,
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };