/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Lead {
  'id' : bigint,
  'leadType' : T__1,
  'name' : string,
  'propertyId' : [] | [bigint],
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface Property {
  'id' : bigint,
  'status' : T__2,
  'title' : string,
  'featured' : boolean,
  'bedrooms' : [] | [bigint],
  'area' : number,
  'description' : string,
  'areaUnit' : string,
  'category' : T,
  'priceUnit' : string,
  'price' : bigint,
  'location' : string,
}
export interface SellPropertyRequest {
  'id' : bigint,
  'ownerName' : string,
  'propertyType' : T,
  'area' : number,
  'description' : string,
  'email' : string,
  'timestamp' : Time,
  'phone' : string,
  'expectedPrice' : bigint,
  'location' : string,
}
export type T = { 'commercial_land' : null } |
  { 'house' : null } |
  { 'residential_plot' : null } |
  { 'warehouse' : null } |
  { 'franchise_outlet' : null };
export type T__1 = { 'contact' : null } |
  { 'site_visit' : null } |
  { 'property_details' : null } |
  { 'general' : null } |
  { 'sell_property' : null };
export type T__2 = { 'sold' : null } |
  { 'available' : null } |
  { 'under_negotiation' : null };
export type Time = bigint;
export interface _SERVICE {
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getAllSellRequests' : ActorMethod<[], Array<SellPropertyRequest>>,
  'getFeaturedProperties' : ActorMethod<[], Array<Property>>,
  'getPropertiesByCategory' : ActorMethod<[T], Array<Property>>,
  'getProperty' : ActorMethod<[bigint], Property>,
  'submitLead' : ActorMethod<
    [string, string, string, string, T__1, [] | [bigint]],
    undefined
  >,
  'submitSellPropertyRequest' : ActorMethod<
    [string, string, string, T, string, number, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];