/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Lead {
    id: bigint;
    leadType: T__1;
    name: string;
    propertyId?: bigint;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
}
export interface Property {
    id: bigint;
    status: T__2;
    title: string;
    featured: boolean;
    bedrooms?: bigint;
    area: number;
    description: string;
    areaUnit: string;
    category: T;
    priceUnit: string;
    price: bigint;
    location: string;
}
export type Time = bigint;
export interface SellPropertyRequest {
    id: bigint;
    ownerName: string;
    propertyType: T;
    area: number;
    description: string;
    email: string;
    timestamp: Time;
    phone: string;
    expectedPrice: bigint;
    location: string;
}
export enum T {
    commercial_land = "commercial_land",
    house = "house",
    residential_plot = "residential_plot",
    warehouse = "warehouse",
    franchise_outlet = "franchise_outlet"
}
export enum T__1 {
    contact = "contact",
    site_visit = "site_visit",
    property_details = "property_details",
    general = "general",
    sell_property = "sell_property"
}
export enum T__2 {
    sold = "sold",
    available = "available",
    under_negotiation = "under_negotiation"
}
export interface backendInterface {
    getAllLeads(): Promise<Array<Lead>>;
    getAllProperties(): Promise<Array<Property>>;
    getAllSellRequests(): Promise<Array<SellPropertyRequest>>;
    getFeaturedProperties(): Promise<Array<Property>>;
    getPropertiesByCategory(category: T): Promise<Array<Property>>;
    getProperty(id: bigint): Promise<Property>;
    submitLead(name: string, phone: string, email: string, message: string, leadType: T__1, propertyId: bigint | null): Promise<void>;
    submitSellPropertyRequest(ownerName: string, phone: string, email: string, propertyType: T, location: string, area: number, expectedPrice: bigint, description: string): Promise<void>;
}
import type { Lead as _Lead, Property as _Property, SellPropertyRequest as _SellPropertyRequest, T as _T, T__1 as _T__1, T__2 as _T__2, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeads();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeads();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProperties();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProperties();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSellRequests(): Promise<Array<SellPropertyRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSellRequests();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSellRequests();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedProperties();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedProperties();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertiesByCategory(arg0: T): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertiesByCategory(to_candid_T_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertiesByCategory(to_candid_T_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperty(arg0: bigint): Promise<Property> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperty(arg0);
                return from_candid_Property_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperty(arg0);
            return from_candid_Property_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitLead(arg0: string, arg1: string, arg2: string, arg3: string, arg4: T__1, arg5: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLead(arg0, arg1, arg2, arg3, to_candid_T__1_n19(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLead(arg0, arg1, arg2, arg3, to_candid_T__1_n19(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async submitSellPropertyRequest(arg0: string, arg1: string, arg2: string, arg3: T, arg4: string, arg5: number, arg6: bigint, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSellPropertyRequest(arg0, arg1, arg2, to_candid_T_n17(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSellPropertyRequest(arg0, arg1, arg2, to_candid_T_n17(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
            return result;
        }
    }
}
function from_candid_Lead_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Property_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Property): Property {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_SellPropertyRequest_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SellPropertyRequest): SellPropertyRequest {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_T__1_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__1): T__1 {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_T__2_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__2): T__2 {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_T_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T): T {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    ownerName: string;
    propertyType: _T;
    area: number;
    description: string;
    email: string;
    timestamp: _Time;
    phone: string;
    expectedPrice: bigint;
    location: string;
}): {
    id: bigint;
    ownerName: string;
    propertyType: T;
    area: number;
    description: string;
    email: string;
    timestamp: Time;
    phone: string;
    expectedPrice: bigint;
    location: string;
} {
    return {
        id: value.id,
        ownerName: value.ownerName,
        propertyType: from_candid_T_n12(_uploadFile, _downloadFile, value.propertyType),
        area: value.area,
        description: value.description,
        email: value.email,
        timestamp: value.timestamp,
        phone: value.phone,
        expectedPrice: value.expectedPrice,
        location: value.location
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    leadType: _T__1;
    name: string;
    propertyId: [] | [bigint];
    email: string;
    message: string;
    timestamp: _Time;
    phone: string;
}): {
    id: bigint;
    leadType: T__1;
    name: string;
    propertyId?: bigint;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
} {
    return {
        id: value.id,
        leadType: from_candid_T__1_n4(_uploadFile, _downloadFile, value.leadType),
        name: value.name,
        propertyId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.propertyId)),
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        phone: value.phone
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _T__2;
    title: string;
    featured: boolean;
    bedrooms: [] | [bigint];
    area: number;
    description: string;
    areaUnit: string;
    category: _T;
    priceUnit: string;
    price: bigint;
    location: string;
}): {
    id: bigint;
    status: T__2;
    title: string;
    featured: boolean;
    bedrooms?: bigint;
    area: number;
    description: string;
    areaUnit: string;
    category: T;
    priceUnit: string;
    price: bigint;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_T__2_n10(_uploadFile, _downloadFile, value.status),
        title: value.title,
        featured: value.featured,
        bedrooms: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.bedrooms)),
        area: value.area,
        description: value.description,
        areaUnit: value.areaUnit,
        category: from_candid_T_n12(_uploadFile, _downloadFile, value.category),
        priceUnit: value.priceUnit,
        price: value.price,
        location: value.location
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sold: null;
} | {
    available: null;
} | {
    under_negotiation: null;
}): T__2 {
    return "sold" in value ? T__2.sold : "available" in value ? T__2.available : "under_negotiation" in value ? T__2.under_negotiation : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    commercial_land: null;
} | {
    house: null;
} | {
    residential_plot: null;
} | {
    warehouse: null;
} | {
    franchise_outlet: null;
}): T {
    return "commercial_land" in value ? T.commercial_land : "house" in value ? T.house : "residential_plot" in value ? T.residential_plot : "warehouse" in value ? T.warehouse : "franchise_outlet" in value ? T.franchise_outlet : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact: null;
} | {
    site_visit: null;
} | {
    property_details: null;
} | {
    general: null;
} | {
    sell_property: null;
}): T__1 {
    return "contact" in value ? T__1.contact : "site_visit" in value ? T__1.site_visit : "property_details" in value ? T__1.property_details : "general" in value ? T__1.general : "sell_property" in value ? T__1.sell_property : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SellPropertyRequest>): Array<SellPropertyRequest> {
    return value.map((x)=>from_candid_SellPropertyRequest_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Property>): Array<Property> {
    return value.map((x)=>from_candid_Property_n8(_uploadFile, _downloadFile, x));
}
function to_candid_T__1_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T__1): _T__1 {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_T_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): _T {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): {
    commercial_land: null;
} | {
    house: null;
} | {
    residential_plot: null;
} | {
    warehouse: null;
} | {
    franchise_outlet: null;
} {
    return value == T.commercial_land ? {
        commercial_land: null
    } : value == T.house ? {
        house: null
    } : value == T.residential_plot ? {
        residential_plot: null
    } : value == T.warehouse ? {
        warehouse: null
    } : value == T.franchise_outlet ? {
        franchise_outlet: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T__1): {
    contact: null;
} | {
    site_visit: null;
} | {
    property_details: null;
} | {
    general: null;
} | {
    sell_property: null;
} {
    return value == T__1.contact ? {
        contact: null
    } : value == T__1.site_visit ? {
        site_visit: null
    } : value == T__1.property_details ? {
        property_details: null
    } : value == T__1.general ? {
        general: null
    } : value == T__1.sell_property ? {
        sell_property: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
